[package]
name = "barnes-hut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.1"
image = "0.24.9"
rand = "0.8.5"
minifb = "0.27.0"
ndarray = "0.16.1"